# Generated by Django 4.1.2 on 2022-10-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Categories",),
        migrations.DeleteModel(name="Menu",),
    ]
