# Generated by Django 4.1.2 on 2022-10-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login", name="username", field=models.CharField(max_length=200),
        ),
    ]
